# cloudbuild.yaml
steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app', '.']

  # Step 2: Push image to Container Registry or Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-app']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'my-app',
        '--image',
        'gcr.io/$PROJECT_ID/my-app',
        '--region',
        'asia-southeast2',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

images:
  - gcr.io/$PROJECT_ID/my-app
